### ISSUE TITLE
LLVM/Clang monolithic and standalone builds

### ISSUE THREAD

**Issue by scsijon** [kisslinux/repo#121]
Sorry, couldn't find the answer in your docs, so asking here.

Can KISS work in a pure musl/clang environment with no libc, etc components?

If so i'll try it out, else like many other package systems, I shall have to forget it.

I'm looking for a new packaging system (source > compiled) I can work with to create a new Quirky (Puppy) Linux Base, rather than use an existing base (debuan, gentoo, ubuntu, etc.) as most are working with.

And i'm looking at moving from libc/glibc/??? as the base to musl/clang/llvm.

thanks

**Comment by konimex** [comment]
I've been trying this for a few days. In my case, basically:

1. Straight monolithic unified (llvm, clang, compiler-rt, libc++{,abi}, libunwind, lld) doesn't work in a gcc environment. I had to do split build first. I will try once again with pure Clang since I have gcc-free LLVM/Clang infrastructure now.
2. Builds of compiler-rt in gcc *will* result in clang builds with `--rtlib=compiler-rt` segfault. So I have to use Clang from Pass 1 to build compiler-rt first.
3. I don't know if g++ actually has the CXXFLAGS for this, but it cannot build with compiler-rt. So for my pass 2 clang build I have to use 9 additional CXXFLAGS to build it with libc++, *including libgcc*. Only then I can build pass 3 which basically builds clang with compiler-rt instead of gcc.

**Comment by konimex** [comment]
> I will try once again with pure Clang since I have gcc-free LLVM/Clang infrastructure now.

Good news! Complete unified LLVM build now works after installing LLVM (Pass 1) -> Clang (Pass 1) -> compiler-rt -> libunwind -> libc++abi -> libc++ -> LLVM (Pass 2) -> Clang (Pass 2) -> Clang (Pass 3). Then I build my LLVM unified package using the pass 3 clang. It finally worked.

However, the question of "whether this package works using musl/clang only" would remain a mystery for now since I'm planning to take it to the extreme and fully use LLVM binutils and replace all the remaining GNU utilities.

**Comment by dylanaraps** [comment]
It might make more sense for us to "bootstrap" llvm by providing an initial llvm-suite which is entirely standalone. Though I think this is best left to a user/third-party repository.

Things may improve in llvm-10 (I hope they do). Until we can do this in a simple one-step process I don't think it's suitable for the official repositories. 

I urge anyone wanting to go down this route to have a look at @konimex's repository here: https://github.com/konimex/kiss-llvm
