### ISSUE TITLE
busybox: can't build on pure LLVM/Clang system

### ISSUE THREAD

**Issue by jelinekto** [kisslinux/repo#157]
I'm experimenting with @konimex's kiss-llvm repo and can't build `busybox` because `make` keeps insisting on calling the `gcc` binary (I removed `gcc` from my system). Since I'm guessing `busybox` should be buildable with `clang` only (`USE_PORTABLE_CODE` config option assumes a non-`gcc` compiler) and don't seem to be able to work around it myself, I thought I'd ask here.

**Comment by konimex** [comment]
A workaround would be set your `$CC` to Clang. However, I can't help if `cc` (the symlink) is pointed to Clang.

Basically, even if `$CC` is set to `cc`, since Clang doesn't support a few GCC extensions, they detected it per the compiler name instead (see [here](https://git.busybox.net/busybox/tree/Makefile.flags#n50)). Also, setting CFLAGS to `-O2`, `-O3` in clang results in segfault. I haven't tried `USE_PORTABLE_CODE` though, I'll keep that in mind later.

**Comment by dylanaraps** [comment]
Let me know if this fixes the issue or not.

**Comment by dylanaraps** [comment]
NOTE: `USE_PORTABLE_CODE` may be useless. See: https://github.com/mirror/busybox/search?utf8=%E2%9C%93&q=ENABLE_USE_PORTABLE_CODE&type=

**Comment by dylanaraps** [comment]
Pushed a second commit which uses `cc` if `$CC` is unset instead of `gcc`.

**Comment by konimex** [comment]
Yeah, it's an ugly situation. As for the segfaults, you may want to empty all CFLAGS like in https://github.com/wyvertux/wyverkiss/blob/e9c018ed0de7066e0fde22cef241578b806d50ba/core/busybox/build#L15. Not ideal, but it works. And yeah, this needs to be escalated upstream.
