### ISSUE TITLE
Package request: fd

### ISSUE THREAD

**Issue by Jackojc** [kisslinux/repo#18]
`fd` is a sane alternative to `find`. It tries to provide good defaults for 80% of cases. It also has some "smart" features in that it ignores dot folders and adheres to .gitignore . It's also very fast. It makes a good development tool.

**Comment by naltun** [comment]
#40 👍 

Rust is good for utilities, eh?

**Comment by naltun** [comment]
![image](https://user-images.githubusercontent.com/7507990/61684436-79a83380-ace7-11e9-897f-ef16f155f40f.png)

**Comment by Jackojc** [comment]
Rust is great for utilities

**Comment by dylanaraps** [comment]
Rust is now packaged, fire away.

**Comment by whoizit** [comment]
I do not think we should add packages that can be assembled using cargo

**Comment by Jackojc** [comment]
Less hassle if they are managed by kiss.

**Comment by whoizit** [comment]
just 
```
cargo install cargo-update
kiss update && cargo install-update -a
```

**Comment by Jackojc** [comment]
Okay but if you do it for rust it sets a precedent for other languages too and it defeats the purpose of having kiss. I think it's just more convenient to package it like other utilities.

**Comment by whoizit** [comment]
Why we should pack something that already has a package (in cargo)? You can simply add .cargo/bin to $PATH. Keep It Simple Sir.

**Comment by konimex** [comment]
> You can simply add `~/.cargo/bin` to `$PATH`

Yeah, good luck with that if you want to make it system-wide.

----

>Keep It Simple, Sir.

Well by your logic we should do away with `python-*` packages in and just use `pip` for everything! And use `npm` for Node packages such as [bower](https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/bower)! Except that would make your system a bigger mess since you have at least 2 "package manager" at work. Simple, right?

**Comment by dylanaraps** [comment]
Re-open this in https://github.com/kisslinux/community
