### ISSUE TITLE
gtk+3: missing dependency

### ISSUE THREAD

**Issue by sdsddsd1** [kisslinux/repo#187]
Building gtk+3 from a base without xorg before fails because of missing `libxkbcommon`

**Comment by dylanaraps** [comment]
This needs to be fixed in the Wayland repository's depends file. The default GTK+3 build is a Xorg based one and the `libxkbcommon` dependency is only required when Wayland is enabled (optional for Xorg):

```
WAYLAND_DEPENDENCIES="wayland-client >= 1.14.91 wayland-protocols >= 1.14 xkbcommon >= 0.2.0 wayland-cursor >= 1.14.91 wayland-egl"
```

The dependency is set to `maybe` in the build system with the value changing to `yes` when Wayland is enabled. With Xorg, it is set to `no` (when unavailable) and the configure passes.

**Comment by dylanaraps** [comment]
To add. I don't have the `libxkbcommon` package installed and can build/use GTK+3 just fine on Xorg.

```sh
-> kiss l libxkbcommon
-> libxkbcommon not installed
```

**Comment by sdsddsd1** [comment]
Thanks for clarification!
