### ISSUE TITLE
Build nodejs with Intl support

### ISSUE THREAD

**Issue by danteissaias** [kisslinux/repo#203]
I am a huge fan of minimalism and removing unused features but (unfortunately?) jest, one of the most popular nodejs testing framework has a dependency makes use of the regex `/u` flag which requires Intl. I have forked the package into my personal repo for now and removed the `--without-intl` flag, but I don't think it's worth it to break compatibility with one of the most popular node testing frameworks in the "official" repo.

References:
https://github.com/sindresorhus/camelcase/blob/master/index.js#L11 (jest depends on this lib)
https://github.com/nodejs/node/blob/master/doc/api/intl.md

**Comment by dylanaraps** [comment]
NodeJS in KISS is more or less solely there to allow Firefox to build. If Firefox didn't have a compile-time dependency on node, it wouldn't be in the official repositories at all. I've been using node for some side projects and haven't come across issues due to the lack of internationalization support. I don't think this affects everyone's usage of node.

I must say no here. KISS does not support internationalization (only exception being webkit2gtk in Community).  You've done the right thing here by forking the package and customizing it to suit your needs. You've also done the right thing by opening an issue here. Thank you for doing so. :+1:

**Comment by jedahan** [comment]
I wrote it in IRC, but will repeat here to offer a different perspective:

> would you consider enabling internationalization support for nodejs? reasoning is that nodejs is used to build software, and although it makes (some) sense that k1ss will be an english-only distribution, it seems not in great spirit to make it difficult to *create* software that supports different languages

some other things to note:

a) internationalization support in nodejs requires 0 new dependencies
b) i am currently building an api for work and we must support multiple languages, and use nodejs' intl support to achieve this

Of course, I forked and reinstalled and it seems fine, but I wonder if extra/nodejs should be renamed extra/nodejs-firefox or extra/nodejs-build, and I can submit a 'regular' distribution of nodejs to the community repository?
