### ISSUE TITLE
What is "kh" and why is it in the chroot tarball

### ISSUE THREAD

**Issue by AndreiSva** [kisslinux/repo#267]
Basically I've noticed there's a new script in the kiss chroot tarball called "kh". It's not in PATH so I would assume it's only meant for use in a chroot.

Could you please provide a more in depth explanation on what this script is and if it is really needed to be included in a running system?

Thanks.

**Comment by dylanaraps** [comment]
That's the hook I used during the chroot build. If I left it in the tarball, that's my mistake. It removes documentation and otherwise unneeded things to make the tarballs smaller. When you rebuild the system (without the hook), these directories will then exist.

The package manager on your system knows nothing about this file unless you set `KISS_HOOK=/kh` in your environment. It's entirely harmless otherwise.

I am uploading a new chroot tarball without this file. Thanks for letting me know.

**Comment by dylanaraps** [comment]
See: https://kisslinux.xyz/package-manager#6.0 for information about package manager hooks.

**Comment by dylanaraps** [comment]
https://github.com/kisslinux/repo/releases/tag/2021.7-4
