### ISSUE TITLE
xxd disabled?

### ISSUE THREAD

**Issue by ioraff** [kisslinux/repo#348]
Is there a specific reason that `busybox xxd` is not enabled by default? This seems inconsistent with the default inclusion of, for example, `hexdump`.

**Comment by dylanaraps** [comment]
There's no specific reason other than nothing needing this utility (and this utility being otherwise provided by vim which makes its use more undesirable). I will be going through the busybox configuration and trimming it down some. `hexdump` will also likely be disabled by default. The busybox package provides many utilities by default that are of no use to the majority of users. The idea is that you enable anything extra you may need.
